import { useCallback, useState } from 'react'
import { BookOpen, Download, FileArchive, FileKey2, Loader2, Tags } from 'lucide-react'
import { toast } from 'sonner'
import FileUpload from '../components/ui/FileUpload'
import ProcessingOverlay from '../components/ui/ProcessingOverlay'
import ToolHeader from '../components/ui/ToolHeader'
import ToolPageWrapper from '../components/ui/ToolPageWrapper'
import usePageTitle from '../hooks/usePageTitle'
import usePendingFiles from '../hooks/usePendingFiles'
import { readPdfDocumentInfo, updatePdfDocumentInfo, type PdfDocumentInfo, type PdfStructureCleanup } from '../lib/pdf'
import { downloadBlob, triggerDownloadOverlay } from '../lib/utils'

const cleanupDefault:PdfStructureCleanup={removeBookmarks:false,removeAttachments:false,removePageLabels:false}
export default function DocumentInfoPage(){usePageTitle('/document-info');const[file,setFile]=useState<File|null>(null);const[info,setInfo]=useState<PdfDocumentInfo|null>(null);const[cleanup,setCleanup]=useState(cleanupDefault);const[processing,setProcessing]=useState(false)
const handleFile=useCallback(async(files:File[])=>{const next=files[0];if(!next)return;try{setFile(next);setInfo(await readPdfDocumentInfo(next));setCleanup(cleanupDefault)}catch{toast.error('This PDF could not be inspected')}},[]);usePendingFiles(handleFile)
const save=async()=>{if(!file||!info)return;setProcessing(true);try{const{structure,creationDate,modificationDate,...editable}=info;void structure;void creationDate;void modificationDate;const bytes=await updatePdfDocumentInfo(file,editable,cleanup);const blob=new Blob([Uint8Array.from(bytes).buffer],{type:'application/pdf'});triggerDownloadOverlay('Document information updated!',()=>downloadBlob(blob,`updated-${file.name}`))}catch{toast.error('Document information could not be updated')}finally{setProcessing(false)}}
if(!file||!info)return <ToolPageWrapper><ToolHeader title="PDF Document Information" description="Inspect and edit PDF metadata, review structural features, and remove bookmarks, attachments or page labels locally."/><FileUpload onFiles={handleFile} multiple={false}/></ToolPageWrapper>
const set=(key:keyof PdfDocumentInfo,value:string)=>setInfo({...info,[key]:value});return <ToolPageWrapper><ToolHeader title="PDF Document Information" description="Review properties and remove selected catalog structures without uploading the file."/><div className="document-info-grid"><section><h2><Tags/>Editable metadata</h2>{([['title','Title'],['author','Author'],['subject','Subject'],['keywords','Keywords'],['language','Language'],['creator','Creator application'],['producer','PDF producer']] as [keyof PdfDocumentInfo,string][]).map(([key,label])=><label key={key}>{label}<input value={String(info[key])} onChange={event=>set(key,event.target.value)}/></label>)}<div className="document-dates"><span>Created<strong>{info.creationDate||'Not recorded'}</strong></span><span>Last modified<strong>{info.modificationDate||'Not recorded'}</strong></span></div></section><aside><section><h2><FileKey2/>Detected structures</h2><ul><li className={info.structure.hasForm?'present':''}>Interactive form</li><li className={info.structure.hasDigitalSignature?'present':''}>Digital signature</li><li className={info.structure.hasBookmarks?'present':''}>Bookmarks / outline</li><li className={info.structure.hasAttachments?'present':''}>Embedded attachments</li><li className={info.structure.hasPageLabels?'present':''}>Custom page labels</li></ul></section><section><h2><FileArchive/>Structure cleanup</h2><label><input type="checkbox" checked={cleanup.removeBookmarks} disabled={!info.structure.hasBookmarks} onChange={event=>setCleanup({...cleanup,removeBookmarks:event.target.checked})}/><BookOpen/>Remove all bookmarks</label><label><input type="checkbox" checked={cleanup.removeAttachments} disabled={!info.structure.hasAttachments} onChange={event=>setCleanup({...cleanup,removeAttachments:event.target.checked})}/>Remove embedded attachments</label><label><input type="checkbox" checked={cleanup.removePageLabels} disabled={!info.structure.hasPageLabels} onChange={event=>setCleanup({...cleanup,removePageLabels:event.target.checked})}/>Remove custom page labels</label><p>Removing structures is permanent in the downloaded copy. Any modification may invalidate a digital signature.</p></section></aside></div><div className="sticky bottom-4 sticky-bar p-4 flex items-center justify-between"><button className="btn-ghost" onClick={()=>{setFile(null);setInfo(null)}}>Change file</button><button className="btn-primary flex items-center gap-2" disabled={processing} onClick={()=>void save()}>{processing?<Loader2 size={15} className="animate-spin"/>:<Download size={15}/>}Save updated PDF</button></div>{processing&&<ProcessingOverlay message="Updating document information…"/>}</ToolPageWrapper>}
