import { Link } from 'react-router-dom'
import ArticleShell from '../components/content/ArticleShell'
import usePageTitle from '../hooks/usePageTitle'

export default function ReduceScannedPdfGuidePage() {
  usePageTitle('/guides/reduce-scanned-pdf-file-size')
  return (
    <ArticleShell kicker="SCANNED PDF GUIDE" title="How to reduce scanned PDF size without losing readability" summary="Understand why scanned documents are large, remove avoidable weight and reduce PDF MB size while protecting handwriting, stamps, signatures and small print." updated="25 August 2026" readingTime="9 minute read" tool={{ href: '/compress/scanned', label: 'Compress a scanned PDF', note: 'Detect the document type locally, choose a size target and inspect the smaller result before using it.' }}>
      <section><div className="content-callout"><strong>Short answer</strong><p>Keep the original, remove blank or duplicate pages, rotate and crop oversized margins, then compress the page images once. Start with balanced compression and inspect the smallest text and every signature before using the result.</p></div></section>
      <section><h2>Why are scanned documents so large?</h2><p>A scan stores each page mainly as an image. Colour pages, high resolution, photographic backgrounds and wide blank margins can make even a short document large. Scanning at twice the width and height creates roughly four times as many pixels. OCR may add searchable text, but it usually does not remove the page image that dominates the file size.</p><ul><li><strong>Colour:</strong> useful for stamps and photos, but heavier than grayscale text.</li><li><strong>Resolution:</strong> improves fine details until extra pixels stop adding practical readability.</li><li><strong>Background:</strong> shadows, desk edges and paper texture create image detail that must be stored.</li><li><strong>Page count:</strong> every accidental blank or duplicate page adds another full image.</li></ul></section>
      <section><h2>Keep the original scan</h2><p>Work on a copy. A compressed version may be suitable for email or upload but should not replace the best available scan of a signed form, identity document, certificate or archive record. Follow the recipient’s current rules for colour, resolution and file format.</p></section>
      <section><h2>Resize a scanned document the useful way</h2><p>People often search for “resize” when the real goal is a smaller file. Changing the PDF’s paper dimensions alone rarely removes the scan pixels. Reduce the captured image area or image detail instead:</p><ol><li>Use <Link to="/manage">Manage pages</Link> to remove blank, accidental or duplicate pages.</li><li>Rotate pages into their final orientation.</li><li>Use <Link to="/crop-pdf">Crop PDF</Link> to remove wide scanner or desk margins when they are not required.</li><li>Split out pages the recipient did not request.</li><li>If rescanning is possible, align pages and avoid capturing a large desk background.</li><li>Use grayscale for plain text only when colour carries no required information.</li></ol></section>
      <section><h2>Choose reduction based on the content</h2><p>Typed black text usually tolerates more image reduction than faint handwriting, seals, photographs or shaded diagrams. Start with balanced compression and inspect a representative page. For a strict upload maximum, move to stronger compression only when the balanced result is still too large.</p><div className="content-callout"><strong>Do not optimise only for the number</strong><p>A file below the portal limit can still fail its real purpose if names, dates, signatures or reference numbers cannot be read.</p></div></section>
      <section><h2>Verify the downloaded scan</h2><ul><li>Open it on the device you will use to submit.</li><li>Read the smallest print at normal and enlarged zoom.</li><li>Check low-contrast handwriting and every signature.</li><li>Confirm page count, order and orientation.</li><li>If OCR was used, compare names, numbers and technical notation with the image.</li><li>Confirm the finished size is below—not exactly equal to—the stated maximum.</li></ul></section>
      <section><h2>If it is still too large</h2><p>Split the document only if the portal accepts multiple files. Otherwise, rescan oversized or poorly framed pages, then combine the corrected pages and compress once. Avoid repeatedly processing the same reduced copy because each pass can make image defects more visible.</p></section>
      <section><h2>Common scanned PDF size questions</h2><h3>How do I reduce the MB size of a scanned PDF?</h3><p>Remove unneeded pages, enter the real size limit, start with balanced scan compression, and inspect the downloaded copy. Use maximum reduction only if the balanced result is still too large.</p><h3>Can I resize a scanned document without uploading it?</h3><p>Yes. The Lab of PDF scanned-document preset analyzes and compresses supported PDFs in browser memory on your device.</p><h3>What scan resolution should I use?</h3><p>Use the receiving organization’s requirement when one is provided. For ordinary text without a mandated setting, choose the lowest resolution that keeps small print, signatures and codes clearly readable after export.</p><h3>Why did selectable text disappear?</h3><p>Balanced and maximum modes create image-based copies. Use lossless mode when keeping searchable text matters more than the smallest possible file, or run <Link to="/ocr-pdf">local OCR</Link> on the final image-based copy when searchable text is required.</p></section>
    </ArticleShell>
  )
}
