import { useState, useRef } from 'react'
import { Download, Loader2, Play, Save, Workflow } from 'lucide-react'
import JSZip from 'jszip'
import { toast } from 'sonner'
import FileUpload from '../components/ui/FileUpload'
import ProcessingOverlay from '../components/ui/ProcessingOverlay'
import ToolHeader from '../components/ui/ToolHeader'
import ToolPageWrapper from '../components/ui/ToolPageWrapper'
import usePageTitle from '../hooks/usePageTitle'
import { runPdfWorkflow, WORKFLOW_PRESETS, type PdfWorkflowConfig } from '../lib/pdfWorkflow'
import { downloadBlob, formatFileSize, triggerDownloadOverlay } from '../lib/utils'

const DEFAULT_CONFIG: PdfWorkflowConfig = { rotate: 0, pageNumbers: false, watermark: '', compress: 'lossless' }

export default function WorkflowsPage() {
  usePageTitle('/workflows')
  const [files,setFiles]=useState<File[]>([]); const [config,setConfig]=useState<PdfWorkflowConfig>(DEFAULT_CONFIG); const [processing,setProcessing]=useState(false); const [progress,setProgress]=useState(''); const abortRef=useRef<AbortController|null>(null)
  const applyPreset=(key:string)=>setConfig({...WORKFLOW_PRESETS[key].config})
  const savePreset=()=>{localStorage.setItem('labofpdf-workflow',JSON.stringify(config));toast.success('Workflow saved on this device')}
  const loadSaved=()=>{try{const saved=localStorage.getItem('labofpdf-workflow');if(saved)setConfig(JSON.parse(saved));else toast.info('No saved workflow yet')}catch{toast.error('Saved workflow could not be read')}}
  const run=async()=>{if(!files.length)return;const controller=new AbortController();abortRef.current=controller;setProcessing(true);try{const results: {name:string;bytes:Uint8Array}[]=[];for(const [index,file] of files.entries()){const bytes=await runPdfWorkflow(file,config,message=>setProgress(`${file.name} · ${message} · ${index+1}/${files.length}`),controller.signal);results.push({name:`processed-${file.name}`,bytes})}if(results.length===1){const blob=new Blob([Uint8Array.from(results[0].bytes).buffer],{type:'application/pdf'});triggerDownloadOverlay('Workflow complete!',()=>downloadBlob(blob,results[0].name))}else{setProgress('Packaging processed PDFs…');const zip=new JSZip();results.forEach(result=>zip.file(result.name,result.bytes));const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});triggerDownloadOverlay(`${results.length} PDFs ready!`,()=>downloadBlob(blob,'labofpdf-workflow-results.zip'))}}catch(error){toast.error(error instanceof DOMException&&error.name==='AbortError'?'Workflow cancelled':'Workflow could not finish')}finally{setProcessing(false);setProgress('');abortRef.current=null}}
  return <ToolPageWrapper><ToolHeader title="Reusable PDF Workflows" description="Process one or many PDFs through the same local sequence. Presets and custom settings stay on this device."/><section className="workflow-presets"><header><span>QUICK START</span><h2>Choose a practical preset</h2></header><div>{Object.entries(WORKFLOW_PRESETS).map(([key,preset])=><button key={key} onClick={()=>applyPreset(key)}><Workflow/><strong>{preset.name}</strong><span>{preset.description}</span></button>)}</div></section><div className="workflow-builder"><section><h2>1. Add PDF files</h2><FileUpload onFiles={next=>setFiles(current=>[...current,...next])} multiple/><div className="workflow-file-list">{files.map((file,index)=><div key={`${file.name}-${file.lastModified}-${index}`}><span><strong>{file.name}</strong><small>{formatFileSize(file.size)}</small></span><button onClick={()=>setFiles(current=>current.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button></div>)}</div></section><section><h2>2. Configure the sequence</h2><label>Rotate all pages<select value={config.rotate} onChange={event=>setConfig({...config,rotate:Number(event.target.value) as PdfWorkflowConfig['rotate']})}><option value={0}>Do not rotate</option><option value={90}>90° clockwise</option><option value={180}>180°</option><option value={270}>90° counter-clockwise</option></select></label><label className="editor-check"><input type="checkbox" checked={config.pageNumbers} onChange={event=>setConfig({...config,pageNumbers:event.target.checked})}/>Add page numbers</label><label>Watermark text<input value={config.watermark} onChange={event=>setConfig({...config,watermark:event.target.value})} placeholder="Leave blank for none"/></label><label>Compression<select value={config.compress} onChange={event=>setConfig({...config,compress:event.target.value as PdfWorkflowConfig['compress']})}><option value="none">No compression</option><option value="lossless">Lossless optimization</option><option value="balanced">Balanced scan copy</option><option value="aggressive">Maximum reduction</option></select></label><div className="workflow-save-row"><button className="btn-ghost" onClick={savePreset}><Save/>Save locally</button><button className="btn-ghost" onClick={loadSaved}>Load saved</button></div><p>Execution order: rotate → page numbers → watermark → compression. Balanced and maximum compression create image-based pages.</p></section></div><div className="sticky bottom-4 sticky-bar p-4 flex items-center justify-between"><span className="text-sm text-gray-400">{files.length} files · browser-only processing</span><button className="btn-primary flex items-center gap-2" disabled={!files.length||processing} onClick={()=>void run()}>{processing?<Loader2 size={15} className="animate-spin"/>:files.length>1?<Download size={15}/>:<Play size={15}/>}Run workflow</button></div>{processing&&<ProcessingOverlay message={progress} onCancel={()=>abortRef.current?.abort()}/>}</ToolPageWrapper>
}
